# Generated by Django 3.2.16 on 2026-02-24 11:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('referentials', '0001_groups_initial'),
        ('accounts', '0002_enable_rls_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HugoSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('share_summary', models.BooleanField(default=False)),
                ('share_evidence', models.BooleanField(default=False)),
                ('share_verbatim', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hugo_sessions', to='referentials.group')),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hugo_sessions', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hugo_sessions', to='accounts.organisation')),
            ],
            options={
                'db_table': 'hugo_session',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Trace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('referential_item_id', models.UUIDField(blank=True, null=True)),
                ('payload_structured', models.JSONField(default=dict)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traces', to='accounts.organisation')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traces', to='hugo.hugosession')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_traces', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'trace',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HugoMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('LEARNER', 'Learner'), ('ASSISTANT', 'Assistant')], max_length=20)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hugo_messages', to='accounts.organisation')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='hugo.hugosession')),
            ],
            options={
                'db_table': 'hugo_message',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_path', models.CharField(max_length=512)),
                ('meta', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='accounts.organisation')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='hugo.hugosession')),
                ('trace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='hugo.trace')),
            ],
            options={
                'db_table': 'evidence',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LearnerState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('skills_matrix', models.JSONField(default=dict)),
                ('missing_coverage', models.JSONField(default=list)),
                ('open_action_items', models.JSONField(default=list)),
                ('summary', models.TextField(blank=True, max_length=2000)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='learner_states', to='referentials.group')),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learner_states', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learner_states', to='accounts.organisation')),
            ],
            options={
                'db_table': 'learner_state',
                'ordering': ['-updated_at'],
                'unique_together': {('learner', 'group')},
            },
        ),
        migrations.AddConstraint(
            model_name='evidence',
            constraint=models.CheckConstraint(check=models.Q(('trace_id__isnull', False), ('session_id__isnull', False), _connector='OR'), name='evidence_trace_or_session'),
        ),
    ]
