# Generated by Django 5.2.11 on 2026-03-12 15:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_relax_rls_user_bootstrap'),
        ('hugo', '0002_enable_rls'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorPrompt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('prompt_type', models.CharField(choices=[('AFEST_HUGO', 'AFEST Hugo')], default='AFEST_HUGO', max_length=50)),
                ('is_default', models.BooleanField(default=False, help_text='If true, used as default for this organisation and prompt_type when no explicit prompt is set.')),
                ('system_template', models.TextField()),
                ('user_template', models.TextField()),
                ('language', models.CharField(choices=[('fr', 'Français'), ('en', 'English')], default='fr', max_length=8)),
                ('tone', models.CharField(choices=[('COACHING', 'Coaching'), ('NEUTRAL', 'Neutre'), ('FRIENDLY', 'Amical')], default='COACHING', max_length=20)),
                ('max_questions_per_turn', models.PositiveIntegerField(default=1)),
                ('max_tokens', models.PositiveIntegerField(default=150, help_text='Hint for the LLM client about the expected answer length.')),
                ('allow_lists', models.BooleanField(default=False, help_text='If false, templates should avoid requesting bulleted / numbered lists.')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_prompts', to='accounts.organisation')),
            ],
            options={
                'db_table': 'tutor_prompt',
                'ordering': ['organisation_id', 'prompt_type', 'code'],
                'unique_together': {('organisation', 'prompt_type', 'code')},
            },
        ),
        migrations.AddField(
            model_name='hugosession',
            name='tutor_prompt',
            field=models.ForeignKey(blank=True, help_text='Optional prompt configuration for this session. If empty, a suitable default will be used.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='hugo.tutorprompt'),
        ),
    ]
