# Generated by Django 5.2.11 on 2026-03-12 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hugo', '0003_tutorprompt_hugosession_tutor_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorprompt',
            name='default_session_phase',
            field=models.CharField(blank=True, choices=[('opening', 'Opening'), ('exploration', 'Exploration'), ('conceptualization', 'Conceptualization'), ('closure', 'Closure')], help_text='Optional default session phase this prompt is optimized for.', max_length=32),
        ),
        migrations.AddField(
            model_name='tutorprompt',
            name='output_format_mode',
            field=models.CharField(choices=[('single_question', 'Single question'), ('multi_question_numbered', 'Multiple questions, numbered'), ('reflection_block', 'Reflection block')], default='single_question', max_length=64),
        ),
        migrations.AddField(
            model_name='tutorprompt',
            name='regulation_bias_metacognition',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tutorprompt',
            name='regulation_bias_reasoning',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tutorprompt',
            name='regulation_bias_task',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tutorprompt',
            name='sot_profile',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
