# Generated by Django 5.2.11 on 2026-03-13 16:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hugo', '0004_tutorprompt_default_session_phase_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OvhLlm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255, unique=True)),
                ('price_per_million_input', models.CharField(max_length=100)),
                ('price_per_million_output', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'ovh_llm',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='tutorprompt',
            name='ovh_llm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tutor_prompts', to='hugo.ovhllm'),
        ),
    ]
