# Generated by Django 5.2.11 on 2026-03-13 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hugo', '0005_ovhllm_tutorprompt_ovh_llm'),
    ]

    operations = [
        migrations.AddField(
            model_name='ovhllm',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
