# Generated by Django 5.2.11 on 2026-03-13 17:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_relax_rls_user_bootstrap'),
        ('hugo', '0006_ovhllm_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='StarterPrompt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('button', models.CharField(help_text='Label du bouton affiché dans l’UI.', max_length=255)),
                ('question', models.TextField(help_text='Question complète envoyée au tuteur quand on clique.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='starter_prompts', to='accounts.organisation')),
            ],
            options={
                'db_table': 'starter_prompt',
                'ordering': ['organisation_id', 'button'],
            },
        ),
    ]
