# Generated by Django 5.2.11 on 2026-03-16 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hugo', '0007_starterprompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='hugomessage',
            name='llm_request_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='hugomessage',
            name='llm_response_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='starterprompt',
            name='question',
            field=models.TextField(help_text="Question complète envoyée à l'apprenant quand il clique."),
        ),
    ]
