# Generated by Django 5.2.11 on 2026-03-16 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hugo", "0008_hugomessage_llm_request_payload_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="hugosession",
            name="current_phase",
            field=models.CharField(
                choices=[
                    ("opening", "Opening"),
                    ("exploration", "Exploration"),
                    ("conceptualization", "Conceptualization"),
                    ("closure", "Closure"),
                ],
                default="exploration",
                help_text="Current dialogue phase for this session.",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="hugosession",
            name="manual_phase_override",
            field=models.CharField(
                blank=True,
                choices=[
                    ("opening", "Opening"),
                    ("exploration", "Exploration"),
                    ("conceptualization", "Conceptualization"),
                    ("closure", "Closure"),
                ],
                help_text="Optional manual override for phase progression.",
                max_length=32,
                null=True,
            ),
        ),
    ]
