# Generated by Django 5.2.11 on 2026-03-16 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hugo", "0009_hugosession_current_phase_and_override"),
    ]

    operations = [
        migrations.AddField(
            model_name="hugosession",
            name="phase_classifier_enabled",
            field=models.BooleanField(
                blank=True,
                help_text="Optional runtime override for phase classifier enablement.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="hugosession",
            name="phase_classifier_max_input_chars",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Optional runtime override for phase classifier input length cap.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="hugosession",
            name="phase_classifier_max_tokens",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Optional runtime override for phase classifier max_tokens.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="hugosession",
            name="phase_classifier_min_confidence",
            field=models.FloatField(
                blank=True,
                help_text="Optional runtime override for phase classifier confidence threshold (0..1).",
                null=True,
            ),
        ),
    ]
