# Generated by Django 5.2.11 on 2026-03-18 11:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("referentials", "0012_referentialitem_block_and_criteria"),
        ("hugo", "0010_hugosession_phase_classifier_runtime_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="TraceCriterionAssessment",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("status", models.CharField(choices=[("not_seen", "Not seen"), ("partial", "Partial"), ("covered", "Covered")], default="partial", max_length=20)),
                ("confidence", models.FloatField(default=0.0)),
                ("notes", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("criterion", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="trace_assessments", to="referentials.referentialcriterion")),
                ("organisation", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="trace_criterion_assessments", to="accounts.organisation")),
                ("trace", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="criterion_assessments", to="hugo.trace")),
            ],
            options={
                "db_table": "trace_criterion_assessment",
                "ordering": ["-created_at"],
                "unique_together": {("trace", "criterion")},
            },
        ),
    ]
