# Generated by Django 5.2.11 on 2026-03-26 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hugo', '0011_tracecriterionassessment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hugosession',
            name='current_phase',
            field=models.CharField(choices=[('opening', 'Opening'), ('exploration', 'Exploration'), ('deepening', 'Deepening'), ('potential_closure', 'Potential closure')], default='exploration', help_text='Current dialogue phase for this session.', max_length=32),
        ),
        migrations.AlterField(
            model_name='hugosession',
            name='manual_phase_override',
            field=models.CharField(blank=True, choices=[('opening', 'Opening'), ('exploration', 'Exploration'), ('deepening', 'Deepening'), ('potential_closure', 'Potential closure')], help_text='Optional manual override for phase progression.', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='tutorprompt',
            name='default_session_phase',
            field=models.CharField(blank=True, choices=[('opening', 'Opening'), ('exploration', 'Exploration'), ('deepening', 'Deepening'), ('potential_closure', 'Potential closure')], help_text='Optional default session phase this prompt is optimized for.', max_length=32),
        ),
    ]
