# Generated by Django 5.2.11 on 2026-03-26 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hugo', '0012_alter_hugosession_current_phase_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hugosession',
            name='p0_classifier_enabled',
            field=models.BooleanField(blank=True, help_text='Optional runtime override for P0 classifier enablement.', null=True),
        ),
        migrations.AddField(
            model_name='hugosession',
            name='p0_classifier_max_input_chars',
            field=models.PositiveIntegerField(blank=True, help_text='Optional runtime override for P0 classifier input length cap.', null=True),
        ),
        migrations.AddField(
            model_name='hugosession',
            name='p0_classifier_max_tokens',
            field=models.PositiveIntegerField(blank=True, help_text='Optional runtime override for P0 classifier max_tokens.', null=True),
        ),
        migrations.AddField(
            model_name='hugosession',
            name='p0_classifier_min_confidence',
            field=models.FloatField(blank=True, help_text='Optional runtime override for P0 classifier confidence threshold (0..1).', null=True),
        ),
    ]
