# Generated by Django 5.2.13 on 2026-05-11 09:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hugo", "0015_hugosession_is_favorite"),
    ]

    operations = [
        migrations.AddField(
            model_name="hugosession",
            name="conversation_profile_override",
            field=models.CharField(
                blank=True,
                choices=[
                    ("diagnostic", "Diagnostic"),
                    ("reflective_afest", "Réflexif AFEST"),
                    ("knowledge_review", "Savoirs / révision"),
                ],
                help_text="Optional conversation posture override for this session.",
                max_length=32,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="tutorprompt",
            name="conversation_profile",
            field=models.CharField(
                choices=[
                    ("diagnostic", "Diagnostic"),
                    ("reflective_afest", "Réflexif AFEST"),
                    ("knowledge_review", "Savoirs / révision"),
                ],
                default="reflective_afest",
                help_text="Primary tutoring posture attached to this prompt.",
                max_length=32,
            ),
        ),
    ]
