# Generated by Django 5.2.11 on 2026-05-15 11:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_relax_rls_user_bootstrap"),
        ("hugo", "0016_hugosession_conversation_profile_override_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="hugosession",
            name="analytics_state",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Aggregated runtime counters used for observability.",
            ),
        ),
        migrations.AddField(
            model_name="hugosession",
            name="conversation_progress",
            field=models.JSONField(
                blank=True,
                default=None,
                help_text="Persisted product-safe conversation progress contract.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="hugosession",
            name="posture",
            field=models.CharField(
                blank=True,
                choices=[
                    ("diagnostic", "Diagnostic"),
                    ("reflective_afest", "Réflexif AFEST"),
                    ("knowledge_review", "Savoirs / révision"),
                ],
                default="",
                help_text="Resolved posture for the latest runtime turn.",
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="ConversationQualitySignal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("posture", models.CharField(blank=True, default="", max_length=64)),
                ("total_turns", models.IntegerField(default=0)),
                ("active_branches_max", models.IntegerField(default=0)),
                ("final_maturity", models.CharField(default="red", max_length=32)),
                ("posture_switches", models.IntegerField(default=0)),
                ("synthesis_requested", models.BooleanField(default=False)),
                ("evaluation_requested", models.BooleanField(default=False)),
                ("evaluation_was_eligible", models.BooleanField(default=False)),
                ("dispersion_turns", models.IntegerField(default=0)),
                ("stuck_red_turns", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "learner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversation_quality_signals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversation_quality_signals",
                        to="accounts.organisation",
                    ),
                ),
                (
                    "session",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quality_signal",
                        to="hugo.hugosession",
                    ),
                ),
            ],
            options={
                "db_table": "conversation_quality_signal",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TrainerKnowledgeItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "referential_item_id",
                    models.CharField(blank=True, default="", max_length=256),
                ),
                ("content", models.TextField()),
                (
                    "content_type",
                    models.CharField(default="mastery_criterion", max_length=64),
                ),
                ("source_type", models.CharField(default="declared", max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("declared", "declared"),
                            ("derived_provisional", "derived_provisional"),
                            ("validated_trainer", "validated_trainer"),
                        ],
                        default="declared",
                        max_length=32,
                    ),
                ),
                ("confidence_score", models.FloatField(blank=True, null=True)),
                ("provenance_note", models.TextField(blank=True, default="")),
                ("validated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trainer_knowledge_items",
                        to="accounts.organisation",
                    ),
                ),
                (
                    "validated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="validated_knowledge_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "trainer_knowledge_item",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="LearnerThemeMemory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("theme_key", models.CharField(db_index=True, max_length=256)),
                (
                    "referential_item_id",
                    models.CharField(blank=True, default="", max_length=256),
                ),
                ("stabilised_points", models.JSONField(default=list)),
                ("open_loops", models.JSONField(default=list)),
                ("persistent_difficulties", models.JSONField(default=list)),
                (
                    "knowledge_status",
                    models.CharField(
                        choices=[
                            ("declared", "declared"),
                            ("derived_provisional", "derived_provisional"),
                            ("validated_trainer", "validated_trainer"),
                        ],
                        default="declared",
                        max_length=32,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "last_conversation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="theme_memory_records",
                        to="hugo.hugosession",
                    ),
                ),
                (
                    "learner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="theme_memories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learner_theme_memories",
                        to="accounts.organisation",
                    ),
                ),
            ],
            options={
                "db_table": "learner_theme_memory",
                "ordering": ["-updated_at"],
                "unique_together": {("learner", "organisation", "theme_key")},
            },
        ),
    ]
