# Generated by Django 5.2.15 on 2026-06-18 17:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_organisation_default_learner_display_profile'),
        ('hugo', '0018_evaluation_and_conduct_profiles'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationLLMAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('analysis_version', models.CharField(default='d9bis_v1', max_length=32)),
                ('turn_analyses_count', models.PositiveIntegerField(default=0)),
                ('summary_metrics', models.JSONField(default=dict)),
                ('export_scope', models.CharField(default='debug_superadmin_only', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_llm_analyses', to='accounts.organisation')),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='llm_analysis', to='hugo.hugosession')),
            ],
            options={
                'db_table': 'conversation_llm_analysis',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConversationTurnLLMAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('turn_index', models.PositiveIntegerField(default=1)),
                ('analysis_version', models.CharField(default='d9bis_v1', max_length=32)),
                ('quality_signals', models.JSONField(default=dict)),
                ('pedagogical_tags', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('learner_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turn_llm_analyses', to='hugo.hugomessage')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_turn_llm_analyses', to='accounts.organisation')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turn_llm_analyses', to='hugo.hugosession')),
            ],
            options={
                'db_table': 'conversation_turn_llm_analysis',
                'ordering': ['session_id', 'turn_index'],
                'unique_together': {('session', 'learner_message')},
            },
        ),
    ]
