# Generated by Django 3.2.16 on 2026-02-24 11:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_enable_rls_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('params', models.JSONField(default=dict)),
                ('file_path', models.CharField(blank=True, max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_runs', to='accounts.organisation')),
            ],
            options={
                'db_table': 'export_run',
                'ordering': ['-created_at'],
            },
        ),
    ]
