# Generated by Django 3.2.16 on 2026-02-24 11:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_enable_rls_user'),
        ('referentials', '0002_enable_rls'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('source_ref', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referentials', to='accounts.organisation')),
            ],
            options={
                'db_table': 'referential',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ReferentialItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=128)),
                ('title', models.CharField(max_length=512)),
                ('evaluation_criteria', models.JSONField(default=list)),
                ('evaluation_modalities', models.JSONField(default=list)),
                ('expected_evidence', models.JSONField(default=list)),
                ('source_ref', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('referential', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='referentials.referential')),
            ],
            options={
                'db_table': 'referential_item',
                'ordering': ['code'],
                'unique_together': {('referential', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Scale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scales', to='accounts.organisation')),
            ],
            options={
                'db_table': 'scale',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ScaleLevel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level_order', models.PositiveSmallIntegerField(default=0)),
                ('label', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='referentials.scale')),
            ],
            options={
                'db_table': 'scale_level',
                'ordering': ['scale', 'level_order'],
            },
        ),
        migrations.CreateModel(
            name='ReferentialItemOverlay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('enabled', models.BooleanField(default=True)),
                ('example_situations', models.JSONField(default=list)),
                ('example_evidence', models.JSONField(default=list)),
                ('common_mistakes', models.JSONField(default=list)),
                ('coach_questions', models.JSONField(default=list)),
                ('linked_documents', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referential_item_overlays', to='referentials.group')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referential_item_overlays', to='accounts.organisation')),
                ('referential_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overlays', to='referentials.referentialitem')),
            ],
            options={
                'db_table': 'referential_item_overlay',
                'unique_together': {('group', 'referential_item')},
            },
        ),
        migrations.CreateModel(
            name='ReferentialConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referential_configs', to='referentials.group')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referential_configs', to='accounts.organisation')),
                ('referential', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configs', to='referentials.referential')),
                ('scale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referential_configs', to='referentials.scale')),
            ],
            options={
                'db_table': 'referential_config',
                'unique_together': {('group', 'referential')},
            },
        ),
    ]
