# Generated by Django 3.2.16 on 2026-02-26 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_usermanager_bootstrap'),
        ('referentials', '0004_enable_rls_referential'),
    ]

    operations = [
        migrations.AddField(
            model_name='referentialitem',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referential_items', to='accounts.organisation'),
        ),
        migrations.AddField(
            model_name='scalelevel',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scale_levels', to='accounts.organisation'),
        ),
    ]
