# Generated by Django 5.2.11 on 2026-03-12 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referentials', '0008_enable_rls_referential_item_scale_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='llm_backend',
            field=models.CharField(choices=[('OLLAMA', 'Ollama (local)'), ('OVH_AI', 'OVH AI Endpoints')], default='OLLAMA', max_length=20),
        ),
    ]
