# Generated by Django 5.2.11 on 2026-03-13 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hugo', '0006_ovhllm_description'),
        ('referentials', '0009_group_llm_backend'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='default_tutor_prompt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups_with_default_tutor_prompt', to='hugo.tutorprompt'),
        ),
    ]
