# Generated by Django 5.2.11 on 2026-03-16 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("referentials", "0010_group_default_tutor_prompt"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="phase_classifier_enabled",
            field=models.BooleanField(
                blank=True,
                help_text="Optional override for phase classifier enablement at group level.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="group",
            name="phase_classifier_max_input_chars",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Optional override for phase classifier input length cap at group level.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="group",
            name="phase_classifier_max_tokens",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Optional override for phase classifier max_tokens at group level.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="group",
            name="phase_classifier_min_confidence",
            field=models.FloatField(
                blank=True,
                help_text="Optional override for phase classifier confidence threshold at group level (0..1).",
                null=True,
            ),
        ),
    ]
