# Generated by Django 5.2.11 on 2026-03-18 11:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("referentials", "0011_group_phase_classifier_runtime_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="referentialitem",
            name="block_code",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="referentialitem",
            name="block_label",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.CreateModel(
            name="ReferentialCriterion",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("code", models.CharField(max_length=128)),
                ("label", models.CharField(max_length=512)),
                ("order_index", models.PositiveIntegerField(default=0)),
                ("expected_evidence", models.JSONField(default=list)),
                ("question_seeds", models.JSONField(default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organisation", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="referential_criteria", to="accounts.organisation")),
                ("referential_item", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="criteria", to="referentials.referentialitem")),
            ],
            options={
                "db_table": "referential_criterion",
                "ordering": ["referential_item", "order_index", "code"],
                "unique_together": {("referential_item", "code")},
            },
        ),
    ]
