# Generated by Django 5.2.11 on 2026-03-18 11:21

from django.db import migrations


def _normalize_criterion_label(value):
    if isinstance(value, dict):
        value = value.get("label") or value.get("title") or value.get("name") or ""
    return str(value or "").strip()


def backfill_criteria(apps, schema_editor):
    ReferentialItem = apps.get_model("referentials", "ReferentialItem")
    ReferentialCriterion = apps.get_model("referentials", "ReferentialCriterion")

    for item in ReferentialItem.objects.all().iterator():
        raw_criteria = list(item.evaluation_criteria or [])
        seen_codes = set()
        order_index = 0
        for idx, raw in enumerate(raw_criteria, start=1):
            label = _normalize_criterion_label(raw)
            if not label:
                continue
            candidate = f"{item.code}.{idx}"
            code = candidate
            suffix = 1
            while code in seen_codes or ReferentialCriterion.objects.filter(
                referential_item_id=item.id,
                code=code,
            ).exists():
                suffix += 1
                code = f"{candidate}_{suffix}"
            ReferentialCriterion.objects.create(
                organisation_id=item.organisation_id,
                referential_item_id=item.id,
                code=code,
                label=label,
                order_index=order_index,
                expected_evidence=[],
                question_seeds=[],
                is_active=True,
            )
            seen_codes.add(code)
            order_index += 1


def reverse_backfill(apps, schema_editor):
    ReferentialCriterion = apps.get_model("referentials", "ReferentialCriterion")
    ReferentialCriterion.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("referentials", "0012_referentialitem_block_and_criteria"),
    ]

    operations = [
        migrations.RunPython(backfill_criteria, reverse_backfill),
    ]
