# Generated by Django 5.2.11 on 2026-03-18 10:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("referentials", "0013_backfill_referential_criteria"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReferentialActivity",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("code", models.CharField(max_length=64)),
                ("label", models.CharField(max_length=255)),
                ("order_index", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organisation", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="referential_activities", to="accounts.organisation")),
                ("referential", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="activities", to="referentials.referential")),
            ],
            options={
                "db_table": "referential_activity",
                "ordering": ["referential", "order_index", "code"],
                "unique_together": {("referential", "code")},
            },
        ),
        migrations.CreateModel(
            name="ReferentialTask",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("code", models.CharField(max_length=64)),
                ("label", models.CharField(max_length=512)),
                ("order_index", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("activity", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="tasks", to="referentials.referentialactivity")),
                ("organisation", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="referential_tasks", to="accounts.organisation")),
            ],
            options={
                "db_table": "referential_task",
                "ordering": ["activity", "order_index", "code"],
                "unique_together": {("activity", "code")},
            },
        ),
        migrations.CreateModel(
            name="ReferentialCompetencyTask",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("organisation", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="referential_competency_tasks", to="accounts.organisation")),
                ("referential_item", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="competency_tasks", to="referentials.referentialitem")),
                ("task", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="competency_links", to="referentials.referentialtask")),
            ],
            options={
                "db_table": "referential_competency_task",
                "ordering": ["-created_at"],
                "unique_together": {("referential_item", "task")},
            },
        ),
    ]
