# Generated by Cursor on 2026-03-18

import django.db.models.deletion
from django.db import migrations, models


def forwards(apps, schema_editor):
    TutorLearnerLink = apps.get_model("referentials", "TutorLearnerLink")
    GroupMembership = apps.get_model("referentials", "GroupMembership")

    # For each legacy link (tutor+learner without group),
    # create one link per group where both are members.
    legacy_links = TutorLearnerLink.objects.filter(group__isnull=True)
    for link in legacy_links.iterator():
        tutor_id = link.tutor_id
        learner_id = link.learner_id
        org_id = link.organisation_id

        tutor_groups = set(
            GroupMembership.objects.filter(
                organisation_id=org_id,
                user_id=tutor_id,
            ).values_list("group_id", flat=True)
        )
        learner_groups = set(
            GroupMembership.objects.filter(
                organisation_id=org_id,
                user_id=learner_id,
            ).values_list("group_id", flat=True)
        )
        common_group_ids = tutor_groups.intersection(learner_groups)
        for group_id in common_group_ids:
            TutorLearnerLink.objects.get_or_create(
                organisation_id=org_id,
                group_id=group_id,
                tutor_id=tutor_id,
                learner_id=learner_id,
                defaults={},
            )
        # Remove the legacy row (keeps new group-scoped rows)
        link.delete()


def backwards(apps, schema_editor):
    # Best-effort: do not attempt to merge group-scoped links back.
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("referentials", "0014_referential_activity_task_competency_task"),
    ]
    atomic = False

    operations = [
        # 1) Drop legacy unique (tutor, learner) so that we can create multiple
        # links for the same pair across different groups during backfill.
        migrations.AlterUniqueTogether(
            name="tutorlearnerlink",
            unique_together=set(),
        ),
        # 2) Add nullable group to allow backfill.
        migrations.AddField(
            model_name="tutorlearnerlink",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tutor_learner_links",
                to="referentials.group",
            ),
        ),
        # 3) Backfill existing rows.
        migrations.RunPython(forwards, backwards),
        # 4) Make group non-nullable.
        migrations.AlterField(
            model_name="tutorlearnerlink",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tutor_learner_links",
                to="referentials.group",
            ),
        ),
        # 5) New unique constraint scoped by group.
        migrations.AlterUniqueTogether(
            name="tutorlearnerlink",
            unique_together={("group", "tutor", "learner")},
        ),
    ]

