# Generated by Django 5.2.11 on 2026-03-26 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referentials', '0015_tutorlearnerlink_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='p0_classifier_enabled',
            field=models.BooleanField(blank=True, help_text='Optional override for P0 classifier enablement at group level.', null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='p0_classifier_max_input_chars',
            field=models.PositiveIntegerField(blank=True, help_text='Optional override for P0 classifier input length cap at group level.', null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='p0_classifier_max_tokens',
            field=models.PositiveIntegerField(blank=True, help_text='Optional override for P0 classifier max_tokens at group level.', null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='p0_classifier_min_confidence',
            field=models.FloatField(blank=True, help_text='Optional override for P0 classifier confidence threshold at group level (0..1).', null=True),
        ),
    ]
