from django.urls import path
from . import (
    views_analytics,
    views_conduct_profiles,
    views_ovh_llm,
    views_sessions,
    views_starter_prompts,
    views_trainer,
    views_tutor_prompts,
)

urlpatterns = [
    path("sessions/", views_sessions.SessionListCreate.as_view(), name="session_list_create"),
    path("sessions/<uuid:session_id>/", views_sessions.SessionDetail.as_view(), name="session_detail"),
    path("sessions/<uuid:session_id>/phase/", views_sessions.SessionPhaseOverrideView.as_view(), name="session_phase_override"),
    path("sessions/<uuid:session_id>/classifier-config/", views_sessions.SessionClassifierConfigView.as_view(), name="session_classifier_config"),
    path("sessions/<uuid:session_id>/progress/", views_sessions.SessionProgressView.as_view(), name="session_progress"),
    path("sessions/<uuid:session_id>/ui-state/", views_sessions.SessionUiStateView.as_view(), name="session_ui_state"),
    path("sessions/<uuid:session_id>/set-posture/", views_sessions.SessionSetPostureView.as_view(), name="session_set_posture"),
    path("sessions/<uuid:session_id>/request-synthesis/", views_sessions.SessionRequestSynthesisView.as_view(), name="session_request_synthesis"),
    path("sessions/<uuid:session_id>/evaluation-readiness/", views_sessions.SessionEvaluationReadinessView.as_view(), name="session_evaluation_readiness"),
    path("sessions/<uuid:session_id>/request-evaluation/", views_sessions.SessionRequestEvaluationView.as_view(), name="session_request_evaluation"),
    path("sessions/<uuid:session_id>/finalize-evaluation/", views_sessions.SessionFinalizeEvaluationView.as_view(), name="session_finalize_evaluation"),
    path("sessions/<uuid:session_id>/messages/", views_sessions.MessageListCreate.as_view(), name="message_list_create"),
    path("sessions/<uuid:session_id>/messages/stream/", views_sessions.MessageStreamCreate.as_view(), name="message_stream_create"),
    path("sessions/<uuid:session_id>/generate-trace/", views_sessions.GenerateTraceView.as_view(), name="generate_trace"),
    path("sessions/<uuid:session_id>/memory-summary/", views_sessions.SessionMemorySummaryView.as_view(), name="session_memory_summary"),
    path("sessions/<uuid:session_id>/share/", views_sessions.ShareView.as_view(), name="share"),
    path("trainer/knowledge-items/", views_trainer.TrainerKnowledgeItemListView.as_view(), name="trainer_knowledge_list"),
    path("trainer/referential-items/<str:referential_item_id>/elicitation-questions/", views_trainer.TrainerElicitationQuestionsView.as_view(), name="trainer_elicitation_questions"),
    path("trainer/referential-items/<str:referential_item_id>/elicitation-answers/", views_trainer.TrainerElicitationAnswersView.as_view(), name="trainer_elicitation_answers"),
    path("trainer/ingest-document/", views_trainer.TrainerDocumentIngestView.as_view(), name="trainer_document_ingest"),
    path("trainer/knowledge-items/<int:item_id>/validate/", views_trainer.TrainerKnowledgeValidationView.as_view(), name="trainer_knowledge_validate"),
    path("trainer/evaluation-records/", views_trainer.TrainerEvaluationRecordListView.as_view(), name="trainer_evaluation_records"),
    path("trainer/evaluation-records/export/", views_trainer.TrainerEvaluationRecordExportView.as_view(), name="trainer_evaluation_records_export"),
    path("trainer/evaluation-records/<uuid:record_id>/validate/", views_trainer.TrainerEvaluationRecordValidationView.as_view(), name="trainer_evaluation_record_validate"),
    path("analytics/cohort-metrics/", views_analytics.CohortMetricsView.as_view(), name="cohort_metrics"),
    path("analytics/learners/<uuid:learner_id>/progress/", views_analytics.LearnerProgressView.as_view(), name="learner_progress"),
    path("tutor-prompts/", views_tutor_prompts.TutorPromptListCreate.as_view(), name="tutor_prompt_list_create"),
    path("tutor-prompts/<uuid:id>/", views_tutor_prompts.TutorPromptDetail.as_view(), name="tutor_prompt_detail"),
    path("conduct-profiles/", views_conduct_profiles.TutorConductProfileListCreate.as_view(), name="conduct_profile_list_create"),
    path("conduct-profiles/<int:id>/", views_conduct_profiles.TutorConductProfileDetail.as_view(), name="conduct_profile_detail"),
    path("ovh-llms/", views_ovh_llm.OvhLlmListCreate.as_view(), name="ovh_llm_list_create"),
    path("ovh-llms/<uuid:id>/", views_ovh_llm.OvhLlmDetail.as_view(), name="ovh_llm_detail"),
    path("starter-prompts/", views_starter_prompts.StarterPromptListCreate.as_view(), name="starter_prompt_list_create"),
    path("starter-prompts/<uuid:id>/", views_starter_prompts.StarterPromptDetail.as_view(), name="starter_prompt_detail"),
]
